config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('ez2on.urls')),
    path('djmax/', include('djmax.urls')),

    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", 
         content_type='text/plain')),
]

# if settings.DEBUG is False:
#     urlpatterns += [
#         re_path(r'^{{본인 media_url 값}}/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), # 나는 uploads
#         re_path(r'^{{본인 static_url 값}}/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}) # 나는 static
#     ]

djmax/urls.py
from django.urls import path

from . import views
app_name = 'djmax'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    
    path('freestyle/<str:keys>', views.index_level, name='index_level'),
    path('chart/<str:keys>/<str:page_name>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    
    # path('parameter/', views.get_post, name='parameter'),
    # path('tier/<str:keys>', views.index_tier, name='index_tier'),
    # path('test/<str:keys>/<int:level>', views.index_tier, name='index_tier'),

    
]

ez2on/urls.py
from django.urls import path

from . import views
app_name = 'ez2on'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    
    path('standard/<str:keys>', views.index_level, name='index_level'),
    # path('chart/<str:keys>/id=<int:song_id>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    path('chart/<str:keys>/<str:page_name>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    
    # path('standard/<str:keys>/id=<int:song_id>', views.detail_level, name='detail_level'),
    # path('standard/<str:keys>/id=<int:song_id>/<str:difficulty>', views.detail_level),
    # path('info/id=<int:song_id>/', views.detail_info),
    # path('chart/<str:file>', views.detail_chart),
    
    path('course', views.index_course, name='index_course'),
    path('course/<str:keys>', views.index_course, name='index_course'),
    # path('course/<str:keys>/id=<int:course_id>/<int:num>', views.detail_course, name='detail_course'),#코스차트
    path('course/<str:page_name>/<int:num>', views.detail_course, name='detail_course'),#코스차트

    
    # path('parameter/', views.get_post, name='parameter'),
    path('tier/<str:keys>', views.index_tier, name='index_tier'),
    # path('test/<str:keys>/<int:level>', views.index_tier, name='index_tier'),

    #API
    path('api/songs.json', views.api_song),
    path('api/allsongs.json', views.api_allsong),
    path('api/levels.json', views.api_levels),
    path('easyscore', views.easyscore),
    # path('test', views.test),
    
    # path('api/groove.json', views.api_groove),
    # path('api/<str:keys>/groove.json', views.api_groove),

    
]

ez2on/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404      
from django.db.models import Case, Q, When
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator  
from .models import Song, Difficulty, Course, Pattern
import random
from datetime import date, timedelta
from django.conf import settings
from django.core import serializers
from django.http import JsonResponse, HttpResponse

# color_liner={"w":"linear-gradient(to left, #888, #fff, #888);",
#             "b":"linear-gradient(to left, rgb(0,94,159), rgb(106,232,229), rgb(0,94,159));",
#             "g":"linear-gradient(to left, rgb(4,99,17),rgb(22,203,64), #fff,rgb(22,203,64), rgb(4,99,17));"}
color_liner={"w":"linear-gradient(to left,#888,#f5f5f5);",
            "b":"linear-gradient(to left, rgb(0,94,159),#5adcff);",
            "g":"linear-gradient(to left, rgb(4,99,17),rgb(22,203,64));",
            "y":"linear-gradient(to left,#bd9739,#ffd161);",
            "r":"linear-gradient(to left,rgb(212,70,92),rgb(226,85,55));"
            }


xtMap={"4A":{
        "grid": settings.STATIC_URL+"res/grid4K.svg",
        "1":  [  0, 30,color_liner["w"],200,1.0],
        "2":  [ 30, 30,color_liner["b"],200,1.0],
        "3":  [ 60, 30,color_liner["b"],200,1.0],
        "4":  [ 90, 30,color_liner["w"],200,1.0],
        },
        "5A":{
        "grid": settings.STATIC_URL+"res/grid5K.svg",
        "1":  [  0, 24,color_liner["w"],200,1.0],
        "2":  [ 24, 24,color_liner["b"],200,1.0],
        "3":  [ 48, 24,color_liner["w"],200,1.0],
        "4":  [ 72, 24,color_liner["b"],200,1.0],
        "5":  [ 96, 24,color_liner["w"],200,1.0],
        },
        "6A":{
        "grid": settings.STATIC_URL+"res/grid6K.svg",
        "1":  [  0, 20,color_liner["w"],200,1.0],
        "2":  [ 20, 20,color_liner["b"],200,1.0],
        "3":  [ 40, 20,color_liner["w"],200,1.0],
        "4":  [ 60, 20,color_liner["w"],200,1.0],
        "5":  [ 80, 20,color_liner["b"],200,1.0],
        "6":  [ 100,20,color_liner["w"],200,1.0],
        },
        #SDVX
        "6H":{
        "grid": settings.STATIC_URL+"res/grid4K.svg",
        "1":  [  0, 60,color_liner["r"],100,1.0],
        "2":  [ 1,  28,color_liner["w"],200,0.7],
        "3":  [ 31, 28,color_liner["w"],200,0.7],
        "4":  [ 61, 28,color_liner["w"],200,0.7],
        "5":  [ 91, 28,color_liner["w"],200,0.7],
        "6":  [ 60, 60,color_liner["r"],100,1.0],
        },
        "7A":{
        "grid": settings.STATIC_URL+"res/grid7K.svg",
        "1":  [  0, 17,color_liner["w"],200,1.0],
        "2":  [ 17, 15,color_liner["b"],200,1.0],
        "3":  [ 32, 17,color_liner["w"],200,1.0],
        "4":  [ 49, 22,color_liner["y"],200,1.0],
        "5":  [ 71, 17,color_liner["w"],200,1.0],
        "6":  [ 88, 15,color_liner["b"],200,1.0],
        "7":  [ 103,17,color_liner["w"],200,1.0],
        },
        #8키
        "8A":{
        "grid": settings.STATIC_URL+"res/grid8K.svg",
        "1":  [  0, 15,color_liner["w"],200,1.0],
        "2":  [ 15, 15,color_liner["b"],200,1.0],
        "3":  [ 30, 15,color_liner["w"],200,1.0],
        "4":  [ 45, 15,color_liner["b"],200,1.0],
        "5":  [ 60, 15,color_liner["b"],200,1.0],
        "6":  [ 75, 15,color_liner["w"],200,1.0],
        "7":  [ 90, 15,color_liner["b"],200,1.0],
        "8":  [ 105,15,color_liner["w"],200,1.0],
        },
        "8B":{
        "grid": settings.STATIC_URL+"res/grid8K.svg",
        "1":  [  0, 15,color_liner["w"],200,1.0],
        "2":  [ 15, 15,color_liner["b"],200,1.0],
        "3":  [ 30, 15,color_liner["w"],200,1.0],
        "4":  [ 45, 15,color_liner["b"],200,1.0],
        "5":  [ 60, 15,color_liner["w"],200,1.0],
        "6":  [ 75, 15,color_liner["b"],200,1.0],
        "7":  [ 90, 15,color_liner["w"],200,1.0],
        "8":  [ 105,15,color_liner["b"],200,1.0],
        },
        "8C":{
        "grid": settings.STATIC_URL+"res/grid8K.svg",
        "1":  [  0, 15,color_liner["g"],200,1.0],
        "2":  [ 15, 15,color_liner["w"],200,1.0],
        "3":  [ 30, 15,color_liner["b"],200,1.0],
        "4":  [ 45, 15,color_liner["w"],200,1.0],
        "5":  [ 60, 15,color_liner["w"],200,1.0],
        "6":  [ 75, 15,color_liner["b"],200,1.0],
        "7":  [ 90, 15,color_liner["w"],200,1.0],
        "8":  [ 105,15,color_liner["g"],200,1.0],
        },
        "8D":{
        "grid": settings.STATIC_URL+"res/grid8K.svg",
        "1":  [  0, 15,color_liner["g"],200,1.0],
        "2":  [ 15, 15,color_liner["w"],200,1.0],
        "3":  [ 30, 15,color_liner["b"],200,1.0],
        "4":  [ 45, 15,color_liner["w"],200,1.0],
        "5":  [ 60, 15,color_liner["g"],200,1.0],
        "6":  [ 75, 15,color_liner["w"],200,1.0],
        "7":  [ 90, 15,color_liner["b"],200,1.0],
        "8":  [ 105,15,color_liner["w"],200,1.0],
        },
        "8E":{
        "grid": settings.STATIC_URL+"res/grid8K.svg",
        "1":  [  0, 15,color_liner["w"],200,1.0],
        "2":  [ 15, 15,color_liner["b"],200,1.0],
        "3":  [ 30, 15,color_liner["w"],200,1.0],
        "4":  [ 45, 15,color_liner["g"],200,1.0],
        "5":  [ 60, 15,color_liner["g"],200,1.0],
        "6":  [ 75, 15,color_liner["w"],200,1.0],
        "7":  [ 90, 15,color_liner["b"],200,1.0],
        "8":  [ 105,15,color_liner["w"],200,1.0],
        },
        "8F":{
        "grid": settings.STATIC_URL+"res/grid8K.svg",
        "1":  [  0, 15,color_liner["g"],200,1.0],
        "2":  [ 15, 15,color_liner["w"],200,1.0],
        "3":  [ 30, 15,color_liner["b"],200,1.0],
        "4":  [ 45, 15,color_liner["w"],200,1.0],
        "5":  [ 60, 15,color_liner["b"],200,1.0],
        "6":  [ 75, 15,color_liner["w"],200,1.0],
        "7":  [ 90, 15,color_liner["b"],200,1.0],
        "8":  [ 105,15,color_liner["w"],200,1.0],
        },
        "8G":{
        "grid": settings.STATIC_URL+"res/grid8K.svg",
        "1":  [  0, 15,color_liner["w"],200,1.0],
        "2":  [ 15, 15,color_liner["b"],200,1.0],
        "3":  [ 30, 15,color_liner["w"],200,1.0],
        "4":  [ 45, 15,color_liner["b"],200,1.0],
        "5":  [ 60, 15,color_liner["w"],200,1.0],
        "6":  [ 75, 15,color_liner["b"],200,1.0],
        "7":  [ 90, 15,color_liner["w"],200,1.0],
        "8":  [ 105,15,color_liner["g"],200,1.0],
        },
        "8H":{#DJMAX
        "grid": settings.STATIC_URL+"res/grid6K.svg",
        "1":  [  0, 60,color_liner["r"],100,1.0],
        "2":  [  0, 20,color_liner["w"],200,0.7],
        "3":  [ 20, 20,color_liner["b"],200,0.7],
        "4":  [ 40, 18,color_liner["w"],200,0.7],
        "5":  [ 62, 18,color_liner["w"],200,0.7],
        "6":  [ 80, 20,color_liner["b"],200,0.7],
        "7":  [ 100,20,color_liner["w"],200,0.7],
        "8":  [ 60, 60,color_liner["r"],100,1.0],
        },
        "8I":{#AE23S
        "grid": settings.STATIC_URL+"res/grid6K.svg",
        "1":  [  0, 20,color_liner["w"],200,0.7],
        "2":  [ 20, 20,color_liner["b"],200,0.7],
        "3":  [ 40, 18,color_liner["w"],200,0.7],
        "4":  [ 0,  60,color_liner["r"],100,1.0],
        "5":  [ 60, 60,color_liner["r"],100,1.0],
        "6":  [ 62, 18,color_liner["w"],200,0.7],
        "7":  [ 80, 20,color_liner["b"],200,0.7],
        "8":  [ 100,20,color_liner["w"],200,0.7],
        },
        "TRIGER":{#AE23S
        "A":  [ 0,  60,color_liner["b"],50,0.3],
        "B":  [ 60, 60,color_liner["b"],50,0.3],
        },
    }
#키 순서처리
def keyorder(request,key_val):
    if   key_val==4: key_noran="1234"
    elif key_val==5: key_noran="12345"
    elif key_val==6: key_noran="123456"
    elif key_val==7: key_noran="1234567"
    elif key_val==8: key_noran="12345678"
    key_mirror = key_noran[::-1]
    key_random= list(key_noran)
    random.shuffle(key_random)
    key_random=''.join(key_random)

    #플립랜덤 구현
    if   key_val==4: 
        key_left="12"
        key_center=""
        key_right="34"
    elif key_val==5: 
        key_left="12"
        key_center="3"
        key_right="45"
    elif key_val==6: 
        key_left="123"
        key_center=""
        key_right="456"
    elif key_val==7: 
        key_left="123"
        key_center="4"
        key_right="567"
    elif key_val==8: 
        key_left="1234"
        key_center=""
        key_right="5678"
    key_left= list(key_left)
    key_right= list(key_right)
    random.shuffle(key_left)
    random.shuffle(key_right)
    key_left=''.join(key_left)
    key_right=''.join(key_right)

    key_frandom=key_left+key_center+key_right
    key_mfrandom=key_right+key_center+key_left

    #최종 키순서값
    key_order = request.GET.get('order', key_noran) 

    return key_order, key_mirror, key_random, key_frandom, key_mfrandom

#CSS 처리
def innerCSSMake(key_val, key_order, key_type):
    key_char=str(key_val)+key_type
    innerCSS=".bar-note {background-image: url(\""+xtMap[key_char]["grid"]+"\");}\n \
                .note {background: linear-gradient(to left,#888,#f5f5f5); z-index:100;}\n"

    for i in range(key_val):
        innerCSS+=".note-"+str(i)+"{margin-left:"+str(xtMap[key_char][key_order[i]][0])+"px;"+\
                                "width:"+str(xtMap[key_char][key_order[i]][1])+"px;"+\
                                "background:"+xtMap[key_char][key_order[i]][2]+";"+\
                                "z-index:"+str(xtMap[key_char][key_order[i]][3])+";"+\
                                "opacity:"+str(xtMap[key_char][key_order[i]][4])+";}\n"
        
    innerCSS+=".note-A{margin-left:"+str(xtMap["TRIGER"]["A"][0])+"px;"+\
                                "width:"+str(xtMap["TRIGER"]["A"][1])+"px;"+\
                                "background:"+xtMap["TRIGER"]["A"][2]+";"+\
                                "z-index:"+str(xtMap["TRIGER"]["A"][3])+";"+\
                                "opacity:"+str(xtMap["TRIGER"]["A"][4])+";}\n"
    innerCSS+=".note-B{margin-left:"+str(xtMap["TRIGER"]["B"][0])+"px;"+\
                                "width:"+str(xtMap["TRIGER"]["B"][1])+"px;"+\

ez2on/templates/ez2on/index_course.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container my-3">
        <div class="pt-key-text"><span style="color:var(--page-purple);font-size:3em;">{{ key }}</span> COURSE
        </div>
        {% if course_list %}
        {% for item in course_list %}

        <div class="div-box round-box round-box-black pt-song-list">
            <div class="pt-song-list-course-level">{{ item.level }}</div>
            <div class="pt-song-list-title"><span id="name">{{ item.name_kr }}</span></div>
            <div class="pt-song-list-level"><a class="round-box list-level-box pt-level-text pt-course-text
                {% if item.show_pattern %}
                        " href="{% url 'ez2on:detail_course' page_name=item.page_name num=1 %}">
                    {% else %}
                        pt-song-list-level-disabled">
                        {% endif %}
                    1<span>st</span><br></a></div>
            <div class="pt-song-list-level"><a class="round-box list-level-box pt-level-text pt-course-text
                {% if item.show_pattern %}
                " href="{% url 'ez2on:detail_course' page_name=item.page_name num=2 %}">
                    {% else %}
                        pt-song-list-level-disabled">
                        {% endif %}
                    2<span>nd</span><br></a></div>
            <div class="pt-song-list-level"><a class="round-box list-level-box pt-level-text pt-course-text
                {% if item.show_pattern %}
                " href="{% url 'ez2on:detail_course' page_name=item.page_name num=3 %}">
                    {% else %}
                        pt-song-list-level-disabled">
                        {% endif %}
                    3<span>rd</span><br></a></div>
            <div class="pt-song-list-level"><a class="round-box list-level-box pt-level-text pt-course-text
                {% if item.show_pattern %}
                " href="{% url 'ez2on:detail_course' page_name=item.page_name num=4 %}">
                    {% else %}
                        pt-song-list-level-disabled">
                        {% endif %}
                    4<span>th</span><br></a></div>
        </div>
        {% endfor %}
        {% else %}
        
            코스가 없습니다.

        {% endif %}


    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if course_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{{ page_text }}page={{ course_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in course_list.paginator.page_range %}
            {% if course_list.number <= 3 %}
                {% if page_number <= 7 %}
                    {% if page_number == course_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?{{ page_text }}page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?{{ page_text }}page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% elif course_list.number >= num_page|add:"-3" %}
                {% if page_number >= num_page|add:"-7" %}
                    {% if page_number == course_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?{{ page_text }}page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?{{ page_text }}page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            
            {% else %}
                {% if page_number <= course_list.number|add:"3" and page_number >= course_list.number|add:"-3" %}
                    {% if page_number == course_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?{{ page_text }}page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?{{ page_text }}page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if course_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?{{ page_text }}page={{ course_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}

ez2on/templates/ez2on/main.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container my-3">
        　<br>
        <div class="Video_Container" style="max-width:696px;padding-bottom:min(56.25% , 392px);">
            <iframe src="https://www.youtube.com/embed/F3uNPW4k_ls" frameborder="0" width="560" height="315"></iframe>
        </div>
        <br>
        <h1 style="font-weight: bold" >EZ2PATTERN</h1>
        <hr>
        <span style="font-weight: normal"><span style="font-weight: bold">EZ2PATTERN</span>은 <a style="font-weight: bold" href="https://sdvx.in/">sdvx.in</a>을 본따 만들어진 평면 채보 사이트입니다.</span><br>
        <br>
        <table class="table">
            <thead>
                <tr class="table-dark">
                    <th>둘러보기</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <a href="{% url 'ez2on:main_page' %}">EZ2ON REBOOT : R</a>
                        ·
                        <a href="{% url 'djmax:main_page' %}">DJMAX RESPECT V</a>
                    </td>
                </tr>
            </tbody>
            <thead>
                <tr class="table-dark">
                    <th>EZ2ON</th>
                </tr>
            </thead>
                <tbody>
                    <tr>
                        <td>
                            <a href="{% url 'ez2on:index_tier' keys='4K' %}"><span style="color:var(--page-red)">4K</span> TIER</a>
                            ·
                            <a href="{% url 'ez2on:index_tier' keys='5K' %}"><span style="color:var(--page-red)">5K</span> TIER</a>
                            ·
                            <a href="{% url 'ez2on:index_tier' keys='6K' %}"><span style="color:var(--page-red)">6K</span> TIER</a>
                            ·
                            <a href="{% url 'ez2on:index_tier' keys='7K' %}"><span style="color:var(--page-red)">7K</span> TIER</a>
                            ·
                            <a href="{% url 'ez2on:index_tier' keys='8K' %}"><span style="color:var(--page-red)">8K</span> TIER</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="{% url 'ez2on:index_level' keys='4B' %}"><span style="color:var(--page-green)">4K</span> BASIC</a>
                            ·
                            <a href="{% url 'ez2on:index_level' keys='5B' %}"><span style="color:var(--page-green)">5K</span> BASIC</a>
                            ·
                            <a href="{% url 'ez2on:index_level' keys='6B' %}"><span style="color:var(--page-green)">6K</span> BASIC</a>
                            ·
                            <a href="{% url 'ez2on:index_level' keys='8B' %}"><span style="color:var(--page-green)">8K</span> BASIC</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="{% url 'ez2on:index_level' keys='4S' %}"><span style="color:var(--page-blue)">4K</span> STANDARD</a>
                            ·
                            <a href="{% url 'ez2on:index_level' keys='5S' %}"><span style="color:var(--page-blue)">5K</span> STANDARD</a>
                            ·
                            <a href="{% url 'ez2on:index_level' keys='6S' %}"><span style="color:var(--page-blue)">6K</span> STANDARD</a>
                            ·
                            <a href="{% url 'ez2on:index_level' keys='8S' %}"><span style="color:var(--page-blue)">8K</span> STANDARD</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="{% url 'ez2on:index_course' keys='4K' %}"><span style="color:var(--page-purple)">4K</span> COURSE</a>
                            ·
                            <a href="{% url 'ez2on:index_course' keys='5K' %}"><span style="color:var(--page-purple)">5K</span> COURSE</a>
                            ·
                            <a href="{% url 'ez2on:index_course' keys='6K' %}"><span style="color:var(--page-purple)">6K</span> COURSE</a>
                            ·
                            <a href="{% url 'ez2on:index_course' keys='8K' %}"><span style="color:var(--page-purple)">8K</span> COURSE</a>
                            ·
                            <a href="{% url 'ez2on:index_course' keys='SP' %}"><span style="color:var(--page-purple)">SP</span> COURSE</a>
                        </td>
                    </tr>
                </tbody>
        </table>
        <br>
        <h3 style="font-weight: bold" >곡 정보</h3>
        <hr>
        <img src="{% static 'img/ez2on/example/img1.jpg' %}" style="width:min(100%, 662px)"><br><br>
        <span style="font-weight: normal">
            <span style="font-weight: bold">● 체감난이도</span><br>
            <span style="font-weight: bold">S+ - S - A - B - C - D - E - F </span>순으로 체감난이도가 낮아짐<br>
            <br>
            <span style="font-weight: bold">● 그루브레이더</span><br>
            <span style="font-weight: bold">NOTES</span>: 시간 당 노트 수<br>
            <span style="font-weight: bold">CLIMAX</span>: 가장 밀도가 높은 마디의 밀도<br>
            <span style="font-weight: bold">MULTI</span>: 시간 당 동시치기 노트 수<br>
            <span style="font-weight: bold">LONG</span>: 시간 당 롱노트 콤보 수 ÷ BPM<br>
            <span style="font-weight: bold">MAYHEM</span>: 16비트가 아닌 노트 수(셋잇단 곡의 경우 12비트가 아닌 노트 수)<br>
        </span>
        <br>
        <br>
        <h3 style="font-weight: bold" >업데이트 내역</h3>
        <hr>
        <span style="font-weight: normal">
            <!-- 2023년 11월 27일 - EZ2DB 카피로 개발 시작<br> -->
            <!-- 2023년 12월 02일 - 패턴 사이트로 방향 전환<br> -->
            <span style="font-weight: bold">2023년 12월 03일</span> - 사이트 오픈<br>
            <span style="font-weight: bold">2023년 12월 09일</span> - UI 개선<br>
            <span style="font-weight: bold">2023년 12월 09일</span> - EC 2-2 16~20랩 채보 추가<br>
        </span>
        <br>
        <br>
        <h3 style="font-weight: bold" >운영</h3>
        <hr>
        <br>
        <br>
        <h3 style="font-weight: bold" >면책조항</h3>
        <hr>
        <span style="font-weight: normal"><span style="font-weight: bold">EZ2PATTERN</span>은 리듬게임 <a style="font-weight: bold" href="https://store.steampowered.com/app/1477590/EZ2ON_REBOOT__R/">EZ2ON REBOOT : R</a>의 팬사이트입니다.<br>본 사이트의 <span style="font-weight: bold">컨텐츠(텍스트, 디스크 이미지, 패턴 데이터)</span>의 모든 권리는 <a style="font-weight: bold" href="http://neonovice.com/">㈜네오노비스</a>와  <a style="font-weight: bold" href="https://www.squarepixels.co.kr/">스퀘어픽셀즈㈜</a>에게 속해있으며, 해당 데이터를 본 사이트 외에서 이용하여 생기는 모든 책임은 <span style="font-weight: bold">전적으로 본인에게 있습니다.</span><br>
        <a style="font-weight: bold">EZ2ON REBOOT : R</a>은 <span style="font-weight: bold">㈜네오노비스</span>의 등록상표입니다.<br>

        본 사이트의 체감 난이도 값은 <a style="font-weight: bold" href="https://online.ez2db.com/">EZ2DB</a>를 참고하여 작성되었습니다.
</div>
{% endblock %}