config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('ez2on.urls')),
    path('djmax/', include('djmax.urls')),

    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", 
         content_type='text/plain')),
]

# if settings.DEBUG is False:
#     urlpatterns += [
#         re_path(r'^{{본인 media_url 값}}/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), # 나는 uploads
#         re_path(r'^{{본인 static_url 값}}/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}) # 나는 static
#     ]

djmax/urls.py
from django.urls import path

from . import views
app_name = 'djmax'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    
    path('freestyle/<str:keys>', views.index_level, name='index_level'),
    path('chart/<str:keys>/<str:page_name>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    
    # path('parameter/', views.get_post, name='parameter'),
    # path('tier/<str:keys>', views.index_tier, name='index_tier'),
    # path('test/<str:keys>/<int:level>', views.index_tier, name='index_tier'),

    
]

ez2on/urls.py
from django.urls import path

from . import views
app_name = 'ez2on'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    
    path('standard/<str:keys>', views.index_level, name='index_level'),
    # path('chart/<str:keys>/id=<int:song_id>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    path('chart/<str:keys>/<str:page_name>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    
    # path('standard/<str:keys>/id=<int:song_id>', views.detail_level, name='detail_level'),
    # path('standard/<str:keys>/id=<int:song_id>/<str:difficulty>', views.detail_level),
    # path('info/id=<int:song_id>/', views.detail_info),
    # path('chart/<str:file>', views.detail_chart),
    
    path('course', views.index_course, name='index_course'),
    path('course/<str:keys>', views.index_course, name='index_course'),
    # path('course/<str:keys>/id=<int:course_id>/<int:num>', views.detail_course, name='detail_course'),#코스차트
    path('course/<str:page_name>/<int:num>', views.detail_course, name='detail_course'),#코스차트

    
    # path('parameter/', views.get_post, name='parameter'),
    path('tier/<str:keys>', views.index_tier, name='index_tier'),
    # path('test/<str:keys>/<int:level>', views.index_tier, name='index_tier'),

    #API
    path('api/songs.json', views.api_song),
    path('api/allsongs.json', views.api_allsong),
    path('api/levels.json', views.api_levels),
    path('easyscore', views.easyscore),
    # path('test', views.test),
    
    # path('api/groove.json', views.api_groove),
    # path('api/<str:keys>/groove.json', views.api_groove),

    
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required Meta Tags: Site Responsive -->
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Site Description Meta Tags -->
    <meta name="title" content="{{ page_info.title }}">
    <meta name="description" content="{{ page_info.description }}">
    <meta name="keyword" content="{{ page_info.keyword }}">

    <!-- Open Graph Meta Tags -->
    <meta property="og:type" content="website">
    <!-- <meta property="og:image" content="{{ page_info.image }}"> -->
    <meta property="og:title" content="{{ page_info.title }}">
    <meta property="og:url" content="{{ page_info.canonical_url }}">
    <meta property="og:description" content="{{ page_info.description }}">

    <!-- Preferred URL -->
    <link rel="canonical" href="{{ request.canonical_url }}">

    <!-- CSS: Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- CSS: Custom -->
    <link rel="stylesheet" type="text/css"  href="{% static 'css/custom-theme.min.css' %}">
    {% if page_info.game == "ez2on" %}<link rel="stylesheet" type="text/css" href="{% static 'css/ez2on/style.css' %}">
    {% elif page_info.game == "djmax" %}<link rel="stylesheet" type="text/css" href="{% static 'css/djmax/style.css' %}">{% endif %}

    <!-- JS: Bootstrap 5 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  
    <!-- Google AdSense -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    {% if page_info.debug %}
    DEBUG:{{ page_info.debug }}
    {% else %}
    <!-- SCRIPT -->
    {% endif %}
    <!-- Adding Site to Naver -->

    <!-- Favicon -->
    <!-- <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" sizes="any">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" sizes="any"> -->

    <!-- Title -->
    <title>{{ page_info.title }}</title>

    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>

</head>
<body>
<!-- 네비게이션바 -->
{% if page_info.game == "ez2on" %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark navbar-inverse bg-dark border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'ez2on:main_page' %}">EZ2PATTERN</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <span class="nav-link">BASIC 
                        <a class="nav-container-box nav-green" href="{% url 'ez2on:index_level' keys='4B' %}">4K</a>
                        <a class="nav-container-box nav-green" href="{% url 'ez2on:index_level' keys='5B' %}">5K</a>
                        <a class="nav-container-box nav-green" href="{% url 'ez2on:index_level' keys='6B' %}">6K</a>
                        <a class="nav-container-box nav-green" href="{% url 'ez2on:index_level' keys='8B' %}">8K</a>
                    </span>
                </li>
                <li class="nav-item">
                    <span class="nav-link">STANDARD
                        <a class="nav-container-box nav-blue" href="{% url 'ez2on:index_level' keys='4S' %}">4K</a>
                        <a class="nav-container-box nav-blue" href="{% url 'ez2on:index_level' keys='5S' %}">5K</a>
                        <a class="nav-container-box nav-blue" href="{% url 'ez2on:index_level' keys='6S' %}">6K</a>
                        <a class="nav-container-box nav-blue" href="{% url 'ez2on:index_level' keys='8S' %}">8K</a>
                    </span>
                </li>
                <li class="nav-item">
                        <span class="nav-link">COURSE
                        <a class="nav-container-box nav-purple" href="{% url 'ez2on:index_course' keys='4K' %}">4K</a>
                        <a class="nav-container-box nav-purple" href="{% url 'ez2on:index_course' keys='5K' %}">5K</a>
                        <a class="nav-container-box nav-purple" href="{% url 'ez2on:index_course' keys='6K' %}">6K</a>
                        <a class="nav-container-box nav-purple" href="{% url 'ez2on:index_course' keys='8K' %}">8K</a>
                        <a class="nav-container-box nav-purple" href="{% url 'ez2on:index_course' keys='SP' %}">SP</a>
                    </span>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% elif page_info.game == "djmax" %}
<nav class="navbar fixed-top navbar-expand-lg navbar-flame border-bottom">
    <div class="container-fluid" style="font-family:Alternate Gothic No2 D">
        <a class="navbar-brand" href="{% url 'djmax:main_page' %}">EZ2PATTERN</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <span>FREESTYLE 
                        <a class="nav-container-box nav-button" href="{% url 'djmax:index_level' keys='4B' %}">4B</a>
                        <a class="nav-container-box nav-button" href="{% url 'djmax:index_level' keys='5B' %}">5B</a>
                        <a class="nav-container-box nav-button" href="{% url 'djmax:index_level' keys='6B' %}">6B</a>
                        <a class="nav-container-box nav-button" href="{% url 'djmax:index_level' keys='8B' %}">8B</a>
                    </span>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endif %}

{% block content %}
{% endblock %}
</body>
</html>