config/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('ez2on.urls')),
    path('djmax/', include('djmax.urls')),

    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", 
         content_type='text/plain')),
]

# if settings.DEBUG is False:
#     urlpatterns += [
#         re_path(r'^{{본인 media_url 값}}/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), # 나는 uploads
#         re_path(r'^{{본인 static_url 값}}/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}) # 나는 static
#     ]

djmax/urls.py
from django.urls import path

from . import views
app_name = 'djmax'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    
    path('freestyle/<str:keys>', views.index_level, name='index_level'),
    path('chart/<str:keys>/<str:page_name>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    
    # path('parameter/', views.get_post, name='parameter'),
    # path('tier/<str:keys>', views.index_tier, name='index_tier'),
    # path('test/<str:keys>/<int:level>', views.index_tier, name='index_tier'),

    
]

ez2on/urls.py
from django.urls import path

from . import views
app_name = 'ez2on'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    
    path('standard/<str:keys>', views.index_level, name='index_level'),
    # path('chart/<str:keys>/id=<int:song_id>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    path('chart/<str:keys>/<str:page_name>/<str:difficulty>', views.detail_chart, name='detail_chart'),#차트
    
    # path('standard/<str:keys>/id=<int:song_id>', views.detail_level, name='detail_level'),
    # path('standard/<str:keys>/id=<int:song_id>/<str:difficulty>', views.detail_level),
    # path('info/id=<int:song_id>/', views.detail_info),
    # path('chart/<str:file>', views.detail_chart),
    
    path('course', views.index_course, name='index_course'),
    path('course/<str:keys>', views.index_course, name='index_course'),
    # path('course/<str:keys>/id=<int:course_id>/<int:num>', views.detail_course, name='detail_course'),#코스차트
    path('course/<str:page_name>/<int:num>', views.detail_course, name='detail_course'),#코스차트

    
    # path('parameter/', views.get_post, name='parameter'),
    path('tier/<str:keys>', views.index_tier, name='index_tier'),
    # path('test/<str:keys>/<int:level>', views.index_tier, name='index_tier'),

    #API
    path('api/songs.json', views.api_song),
    path('api/allsongs.json', views.api_allsong),
    path('api/levels.json', views.api_levels),
    path('easyscore', views.easyscore),
    # path('test', views.test),
    
    # path('api/groove.json', views.api_groove),
    # path('api/<str:keys>/groove.json', views.api_groove),

    
]

djmax/models.py
from django.db import models

# Create your models here.
class Song(models.Model):
    name_kr       = models.CharField(max_length=100)
    name_kr_order  = models.IntegerField(default=0)
    page_name  = models.CharField(max_length=100,unique=True)
    composer   = models.CharField(max_length=100)
    category   = models.CharField(max_length=10,default="ALL")

    min_bpm      = models.FloatField(default=0)
    max_bpm      = models.FloatField(default=0)

    update_date = models.DateField(auto_now_add=False)
    deleted = models.BooleanField(default = False)
    
    def __str__(self):
        return self.name_kr

class Difficulty(models.Model):
    DEFAULT_KEY="NA"
    KEY_CHOICES = [
        (DEFAULT_KEY, "Not Value"),
        ("4B", "4BUTTON"),
        ("5B", "5BUTTON"),
        ("6B", "6BUTTON"),
        ("8B", "8BUTTON"),
    ]
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    key = models.CharField(max_length=2,choices=KEY_CHOICES, default=DEFAULT_KEY)

    NM_level  = models.IntegerField(default=0)
    HD_level  = models.IntegerField(default=0)
    MX_level  = models.IntegerField(default=0)
    SC_level  = models.IntegerField(default=0)
    NM_pattern = models.BooleanField(default = False)
    HD_pattern = models.BooleanField(default = False)
    MX_pattern = models.BooleanField(default = False)
    SC_pattern = models.BooleanField(default = False)
    def __str__(self):
        return str(self.song.name_kr)+'|'+str(self.key)
    
class Pattern(models.Model):
    DEFAULT_KEY="NA"
    KEY_CHOICES = [
        (DEFAULT_KEY, "Not Value"),
        ("4B", "4BUTTON"),
        ("5B", "5BUTTON"),
        ("6B", "6BUTTON"),
        ("8B", "8BUTTON"),
    ]
    key = models.CharField(max_length=2,choices=KEY_CHOICES, default=DEFAULT_KEY)
    level = models.IntegerField(default=0) 
    floor = models.FloatField(default=0) 
    difficulty = models.CharField(max_length=40)
    notes        = models.IntegerField(default=0)

    # notes_groove        = models.IntegerField(default=0)
    # climax_groove        = models.IntegerField(default=0)
    # multi_groove        = models.IntegerField(default=0)
    # long_groove       = models.IntegerField(default=0)
    # mayhem_groove       = models.IntegerField(default=0)

    pattern_maker = models.CharField(max_length=40)
    show_pattern   = models.BooleanField(default = False)

    def __str__(self):
        return self.song.name_kr+"|"+self.key+" "+self.difficulty

    song = models.ForeignKey(Song, on_delete=models.CASCADE)

djmax/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404      
from django.db.models import Case, Q, When
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator  
from .models import Song, Difficulty, Pattern
import random
from datetime import date, timedelta
from django.conf import settings


# color_liner={"w":"linear-gradient(to left, #888, #fff, #888);",
#             "b":"linear-gradient(to left, rgb(0,94,159), rgb(106,232,229), rgb(0,94,159));",
#             "g":"linear-gradient(to left, rgb(4,99,17),rgb(22,203,64), #fff,rgb(22,203,64), rgb(4,99,17));"}
color_liner={"w":"linear-gradient(to left,#888,#f5f5f5);",
            "b":"linear-gradient(to left, rgb(0,94,159),#5adcff);",
            "g":"linear-gradient(to left, rgb(4,99,17),rgb(22,203,64));",
            "y":"linear-gradient(to left,#bd9739,#ffd161);",
            "r":"linear-gradient(to left,rgb(212,70,92),rgb(226,85,55));",
            "v":"linear-gradient(to left,rgb(196,44,251),rgb(154,83,249));",
            "side":"linear-gradient(to left,rgb(58, 153, 153),rgb(51,204,204));"
            }


xtMap={"4A":{
        "grid": settings.STATIC_URL+"res/grid4K.svg",
        "1":  [  0, 30,color_liner["y"],200,1.0],
        "2":  [ 30, 30,color_liner["b"],200,1.0],
        "3":  [ 60, 30,color_liner["b"],200,1.0],
        "4":  [ 90, 30,color_liner["y"],200,1.0],
        "A":  [ 0,  60,color_liner["side"],50,0.7],
        "B":  [ 60, 60,color_liner["side"],50,0.7],
        },
        "5A":{
        "grid": settings.STATIC_URL+"res/grid5K.svg",
        "1":  [  0, 24,color_liner["y"],200,1.0],
        "2":  [ 24, 24,color_liner["b"],200,1.0],
        "3":  [ 48, 24,color_liner["y"],200,1.0],
        "4":  [ 72, 24,color_liner["b"],200,1.0],
        "5":  [ 96, 24,color_liner["y"],200,1.0],
        "A":  [ 0,  60,color_liner["side"],50,0.7],
        "B":  [ 60, 60,color_liner["side"],50,0.7],
        },
        "6A":{
        "grid": settings.STATIC_URL+"res/grid6K.svg",
        "1":  [  0, 20,color_liner["y"],200,1.0],
        "2":  [ 20, 20,color_liner["b"],200,1.0],
        "3":  [ 40, 20,color_liner["y"],200,1.0],
        "4":  [ 60, 20,color_liner["y"],200,1.0],
        "5":  [ 80, 20,color_liner["b"],200,1.0],
        "6":  [ 100,20,color_liner["y"],200,1.0],
        "A":  [ 0,  60,color_liner["side"],50,0.7],
        "B":  [ 60, 60,color_liner["side"],50,0.7],
        },
        #8키
        "8A":{#DJMAX
        "grid": settings.STATIC_URL+"res/grid6K.svg",
        "1":  [  0, 20,color_liner["y"],200,1.0],
        "2":  [ 20, 20,color_liner["b"],200,1.0],
        "3":  [ 40, 20,color_liner["y"],200,1.0],
        "4":  [ 60, 20,color_liner["y"],200,1.0],
        "5":  [ 80, 20,color_liner["b"],200,1.0],
        "6":  [ 100,20,color_liner["y"],200,1.0],
        "7":  [  0, 60,color_liner["r"],100,0.9],
        "8":  [ 60, 60,color_liner["r"],100,0.9],
        "A":  [ 0,  60,color_liner["side"],50,0.7],
        "B":  [ 60, 60,color_liner["side"],50,0.7],
        },
        "10A":{#DJMAX
        "grid": settings.STATIC_URL+"res/grid6K.svg",
        "1":  [  0, 20,color_liner["y"],200,1.0],
        "2":  [ 20, 20,color_liner["b"],200,1.0],
        "3":  [ 40, 20,color_liner["y"],200,1.0],
        "4":  [ 60, 20,color_liner["y"],200,1.0],
        "5":  [ 80, 20,color_liner["b"],200,1.0],
        "6":  [ 100,20,color_liner["y"],200,1.0],
        "7":  [  0, 60,color_liner["r"],100,0.9],
        "8":  [ 60, 60,color_liner["r"],100,0.9],
        "9":  [  0, 60,color_liner["v"],70,0.9],
        "0":  [ 60, 60,color_liner["v"],70,0.9],
        "A":  [ 0,  60,color_liner["side"],50,0.7],
        "B":  [ 60, 60,color_liner["side"],50,0.7],
        },
        "SIDE":{#AE23S
        "7":  [  0, 60,color_liner["r"],100,0.9],
        "8":  [ 60, 60,color_liner["r"],100,0.9],
        "A":  [ 0,  60,color_liner["side"],50,0.7],
        "B":  [ 60, 60,color_liner["side"],50,0.7],
        },
    }
#키 순서처리
def keyorder(request,key_val):
    if   key_val==4: key_noran="1234AB"
    elif key_val==5: key_noran="12345AB"
    elif key_val==6: key_noran="123456AB"
    elif key_val==8: key_noran="12345678AB"
    elif key_val==10: key_noran="1234567890AB"

    #미러 구현
    key_mirror = key_noran.replace("AB","").replace("78","").replace("90","")[::-1]
    if key_val==8:
        key_mirror=key_mirror+"87"
    elif key_val==10:
        key_mirror=key_mirror+"8709"
    key_mirror=key_mirror+"BA"

    #랜덤 구현
    key_random= list(key_noran.replace("AB","").replace("78","").replace("90",""))
    key_tri_ran=list("AB")
    random.shuffle(key_random)
    random.shuffle(key_tri_ran)
    key_random=''.join(key_random)
    key_tri_ran=''.join(key_tri_ran)  
    if key_val==8:
        key_random=key_random+key_tri_ran.replace("A","7").replace("B","8")
    elif key_val==10:
        key_random=key_random+key_tri_ran.replace("A","7").replace("B","8")+key_tri_ran.replace("A","9").replace("B","0")
    key_random=key_random+key_tri_ran

    #하프랜덤 구현
    if   key_val==4: 
        key_left="12"
        key_center=""
        key_right="34"
        key_tri="AB"
    elif key_val==5: 
        key_left="12"
        key_center="3"
        key_right="45"
        key_tri="AB"
    elif key_val==6: 
        key_left="123"
        key_center=""
        key_right="456"
        key_tri="AB"
    elif key_val==8: 
        key_left="123"
        key_center=""
        key_right="456"
        key_tri="78AB"
    elif key_val==10: 
        key_left="123"
        key_center=""
        key_right="456"
        key_tri="7890AB"

    key_left= list(key_left)
    key_right= list(key_right)
    random.shuffle(key_left)
    random.shuffle(key_right)
    key_left=''.join(key_left)
    key_right=''.join(key_right)

    key_hrandom=key_left+key_center+key_right+key_tri

    #최종 키순서값
    key_order = request.GET.get('order', key_noran) 

    return key_order, key_mirror, key_random, key_hrandom

#CSS 처리
def innerCSSMake(key_val, key_order, key_type, fx_pattern=False):
    key_char=str(key_val)+key_type
    innerCSS=".bar-note {background-image: url(\""+xtMap[key_char]["grid"]+"\");}\n \
                .note {background: linear-gradient(to left,#888,#f5f5f5); z-index:100;}\n"

    for i in range(key_val):
        innerCSS+=".note-"+str(i)+"{margin-left:"+str(xtMap[key_char][key_order[i]][0])+"px;"+\
                                "width:"+str(xtMap[key_char][key_order[i]][1])+"px;"+\
                                "background:"+xtMap[key_char][key_order[i]][2]+";"+\
                                "z-index:"+str(xtMap[key_char][key_order[i]][3])+";"+\
                                "opacity:"+str(xtMap[key_char][key_order[i]][4])+";}\n"
        
    innerCSS+=".long.note-"+key_order[-2]+"{margin-left:"+str(xtMap["SIDE"]["A"][0])+"px;"+\
                                "width:"+str(xtMap["SIDE"]["A"][1])+"px;"+\
                                "background:"+xtMap["SIDE"]["A"][2]+";"+\
                                "z-index:"+str(xtMap["SIDE"]["A"][3])+";"+\
                                "opacity:"+str(xtMap["SIDE"]["A"][4])+";}\n"
    innerCSS+=".long.note-"+key_order[-1]+"{margin-left:"+str(xtMap["SIDE"]["B"][0])+"px;"+\
                                "width:"+str(xtMap["SIDE"]["B"][1])+"px;"+\
                                "background:"+xtMap["SIDE"]["B"][2]+";"+\
                                "z-index:"+str(xtMap["SIDE"]["B"][3])+";"+\
                                "opacity:"+str(xtMap["SIDE"]["B"][4])+";}\n"
    if fx_pattern:
        innerCSS+=".note-"+key_order[-2].replace("A","6").replace("B","7")+\
                                    "{margin-left:"+str(xtMap["SIDE"]["7"][0])+"px;"+\
                                    "width:"+str(xtMap["SIDE"]["7"][1])+"px;"+\
                                    "background:"+xtMap["SIDE"]["7"][2]+";"+\
                                    "z-index:"+str(xtMap["SIDE"]["7"][3])+";"+\
                                    "opacity:"+str(xtMap["SIDE"]["7"][4])+";}\n"
        innerCSS+=".note-"+key_order[-1].replace("A","6").replace("B","7")+\
                                    "{margin-left:"+str(xtMap["SIDE"]["8"][0])+"px;"+\
                                    "width:"+str(xtMap["SIDE"]["8"][1])+"px;"+\
                                    "background:"+xtMap["SIDE"]["8"][2]+";"+\
                                    "z-index:"+str(xtMap["SIDE"]["8"][3])+";"+\
                                    "opacity:"+str(xtMap["SIDE"]["8"][4])+";}\n"

    return innerCSS

def main_page(request):
    page_info={
        'title': "EZ2PATTERN(DJMAX)",
        'description': "EZ2PATTERN(DJMAX)",
        'canonical_url' : request.build_absolute_uri(request.path),
        'keyword':  "DJMAX",
        'game':"djmax",
        'debug':settings.DEBUG
    }
    context = {
        'page_info': page_info
    }
    return render(request,'djmax/main.html', context)

def index_level(request, keys="4S"):

    # GET 값 받아오기
    page = request.GET.get('page', '1')  
    category = request.GET.get('category', 'ALL') 
    level = request.GET.get('level', 'ALL') 
    sclevel = request.GET.get('sclevel', 'ALL') 
    
    #유효성 검사
    if len(page)>3: raise Http404()
    if len(category)>5: raise Http404()
    if len(level)>4: raise Http404()
    if keys not in ['4B', '5B', '6B', '8B']:       
        raise Http404()

    #DB 불러오기
    song_list = Difficulty.objects.filter(key=keys).order_by('-SC_level', '-MX_level', 'song__name_kr_order')
    
    #카테고리 처리
    page_text = ""
    if category!="ALL":
        if category == "NEW":
            song_list = song_list.filter(song__update_date__range=[date.today() - timedelta(days=60), date.today()]).order_by('-song__update_date','song__name_kr_order')
            page_text += "category="+category+"&"
        else:
            song_list = song_list.filter(song__category=category)
            page_text += "category="+category+"&"
    
    #레벨 처리
    level_int=0
    sclevel_int=0
    if level!="ALL":

djmax/templates/djmax/detail_chart.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style type="text/css">
	@import url("{% static 'css/djmax/chart.css' %}");
    {% autoescape off %}
    {{ innerCSS }}
    {% endautoescape %}
    :root {
        --note-height: 1.0
    }
</style>
<script type="text/javascript">
    function BPMPrint(){
        let num1 = {{ song.max_bpm }}
        let num2 = {{ song.min_bpm }}
        if (num1 - num2 < 0.1){document.write(num1);}
        else{document.write(num2+" - "+num1);}
    }
    function page_back(){
        if (document.referrer && // 뒤로 갈 히스토리가 있는 경우 및 우리 시스템에서 링크를 통해 유입된 경우
        (document.referrer.indexOf("{% url 'djmax:main_page' %}") !== -1)) {
            history.back();    // 뒤로가기
        }
        else {// 히스토리가 없는 경우 (URL을 직접 입력하여 유입된 경우)
            location.href = "{% url 'djmax:main_page' %}";    // 메인페이지로 
        }
    }
    function clip(){
        var dummy    = document.createElement("textarea");
        var text    = location.href;        
        document.body.appendChild(dummy);
        dummy.value = text;
        dummy.select();
        document.execCommand("copy");
        document.body.removeChild(dummy);
        alert("링크가 복사되었습니다. 필요하신 곳에 붙여넣기 하세요!\nTYPE: {{ key_type }} / SEED: {{ key_order }}")
    };
</script> 
<div class="view">
    
    <!-- <div class="background-pic" style="background-image: url('{% static 'img/background/' %}{{ song.category }}.webp');"></div> -->
    <div class="background-pic"></div>
    <div class="background-trans"></div>
    <div class="div-box pt-pattern-top-box">
        <div class="song-info">
            <table>
                <tbody>
                    <tr style="font-weight:bold;font-family:Alternate Gothic No2 D">
                        <td>
                            {{ keys }}UTTON TUNES
                        </td>
                    </tr>
                    <tr style="font-size:2em">
                        <td>{{ song.name_kr }}</td>
                    </tr>
                    <tr style="font-size:0.8em; font-family:Alternate Gothic No2 D;font-weight: bold;">
                        <td>{{ song.composer }}</td>
                    </tr>
                    <td style="font-size:0.8em;">
                        BPM <span style="font-family:Alternate Gothic No2 D;font-weight: bold;"><script>BPMPrint();</script></span></td>
                </tbody>
            </table>

            <div style="font-family:Alternate Gothic No2 D;font-weight: bold;background-color:white;width:100px;color:black;text-align:center;">
                {% if difficulty == "MX" %}MAXIMUM
                {% elif difficulty == "HD" %}HARD
                {% elif difficulty == "NM" %}NORMAL
                {% elif difficulty == "SP" %}SPECIAL
                {% elif difficulty == "RD" %}REDESIGN
                {% else %}{{ difficulty }}{% endif %} 
            </div>
            <table style="font-size:0.8em;">
                <tbody>
                    <tr>
                        <td style="padding-right:15px;">level</td><td style="font-family:Alternate Gothic No2 D;font-weight: bold;">{{ pattern_data.level }}</td>
                    </tr>
                    <tr>
                        <td style="padding-right:15px;">floor</td><td style="font-family:Alternate Gothic No2 D;font-weight: bold;">{{ pattern_data.floor }}</td>
                    </tr>
                    <tr>
                        <td style="padding-right:15px;">Notes</td><td style="font-family:Alternate Gothic No2 D;font-weight: bold;">{{ pattern_data.notes }}</td>
                    </tr>
                </tbody>
            </table>


            <br>
            
            SEED: {{ key_order }}<br>
            
            <button onclick="location.href='?{% if key_type != "A" %}type={{ key_type }}{% endif %}'">정배치</button>
            <button onclick="location.href='?{% if key_type != "A" %}type={{ key_type }}&{% endif %}order={{ key_mirror }}'">미러</button>
            <button onclick="location.href='?{% if key_type != "A" %}type={{ key_type }}&{% endif %}order={{ key_random }}'">랜덤</button>
            <button onclick="location.href='?{% if key_type != "A" %}type={{ key_type }}&{% endif %}order={{ key_hrandom }}'">하프랜덤</button><br>
            <button onclick="clip()">링크공유</button>
              <button style="float:right" onclick="page_back()">뒤로가기</button>
        </div>
        
    </div>

    <!-- output -->
    <div>
    {% autoescape off %}
    {{ innerHTML }}
    {% endautoescape %}
    <div>　</div>
    </div>
    <div>　</div>
</div>

{% endblock %}

djmax/templates/djmax/main.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container my-3">
        　<br>
        <div class="Video_Container" style="max-width:696px;padding-bottom:min(56.25% , 392px);">
            <iframe src="https://www.youtube.com/embed/1EJcaxYMZzQ" frameborder="0" width="560" height="315"></iframe>
        </div>
        <br>
        <h1 style="font-weight: bold" >EZ2PATTERN - DJMAX (BETA)</h1>
        <hr>
        <span style="font-weight: normal"><span style="font-weight: bold">EZ2PATTERN</span>은 <a style="font-weight: bold" href="https://sdvx.in/">sdvx.in</a>을 본따 만들어진 평면 채보 사이트입니다.</span><br>
        <br>
        <table class="table">
            <thead>
                <tr class="table-dark">
                    <th>둘러보기</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <a href="{% url 'ez2on:main_page' %}">EZ2ON REBOOT : R</a>
                        ·
                        <a href="{% url 'djmax:main_page' %}">DJMAX RESPECT V</a>
                    </td>
                </tr>
            </tbody>
            <thead>
                <tr class="table-dark">
                    <th>DJMAX</th>
                </tr>
            </thead>
                <tbody>
                    <tr>
                        <td>
                            <a href="{% url 'djmax:index_level' keys='4B' %}">4 BUTTON</a>
                            ·
                            <a href="{% url 'djmax:index_level' keys='5B' %}">5 BUTTON</a>
                            ·
                            <a href="{% url 'djmax:index_level' keys='6B' %}">6 BUTTON</a>
                            ·
                            <a href="{% url 'djmax:index_level' keys='8B' %}">8 BUTTON</a>
                        </td>
                    </tr>
                </tbody>
        </table>
        <br>
        <h3 style="font-weight: bold" >특수패턴(임시)</h3>
        <hr>
        <table class="table">
            <thead>
                <tr class="table-dark">
                    <th>패턴명</th><th>곡</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        [XB SP]
                    </td>
                    <td>
                        <a href="{% url 'djmax:detail_chart' keys='XB' page_name='Fermion' difficulty='SP' %}">Fermion</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        [XB SP]
                    </td>
                    <td>
                        <a href="{% url 'djmax:detail_chart' keys='XB' page_name="We're All Gonna Die" difficulty='SP' %}">We're All Gonna Die</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        [XB SP]
                    </td>
                    <td>
                        <a href="{% url 'djmax:detail_chart' keys='XB' page_name='SON OF SUN ~Extended Mix~' difficulty='SP' %}">SON OF SUN ~Extended Mix~</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        [8B SC]
                    </td>
                    <td>
                        <a href="{% url 'djmax:detail_chart' keys='8B' page_name='SON OF SUN ~Extended Mix~' difficulty='SC' %}">SON OF SUN ~Extended Mix~</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        [5B FX]
                    </td>
                    <td>
                        <a href="{% url 'djmax:detail_chart' keys='5B' page_name='The Four Seasons : Summer 2017' difficulty='FX' %}">The Four Seasons : Summer 2017</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        [5B FX]
                    </td>
                    <td>
                        <a href="{% url 'djmax:detail_chart' keys='5B' page_name='Fundamental' difficulty='FX' %}">Fundamental</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        [5B FX]
                    </td>
                    <td>
                        <a href="{% url 'djmax:detail_chart' keys='5B' page_name='Ikazuchi' difficulty='FX' %}">Ikazuchi</a>
                    </td>
                </tr>
            </tbody>
        </table>
        <br>
        <h3 style="font-weight: bold" >업데이트 내역</h3>
        <hr>
        <span style="font-weight: normal">
            <span style="font-weight: bold">2023년 12월 16일</span> - 사이트 오픈<br>
        </span>
        <br>
        <br>
        <h3 style="font-weight: bold" >운영</h3>
        <hr>
        <span style="font-weight: normal">
            <br>
            현재 페이지의 아이콘 이미지는 V-ARCHIVE 사이트에서 호출하여 동작하고 있습니다.<br>
        </span>
        <br>
        <br>
        <h3 style="font-weight: bold" >면책조항</h3>
        <hr>
        <span style="font-weight: normal"><span style="font-weight: bold">EZ2PATTERN - DJMAX</span>은 리듬게임 <a style="font-weight: bold" href="https://store.steampowered.com/app/960170/DJMAX_RESPECT_V">DJMAX RESPECT V</a>의 팬사이트입니다.<br>본 사이트의 <span style="font-weight: bold">컨텐츠(텍스트, 아이콘 이미지, 패턴 데이터)</span>의 모든 권리는 <a style="font-weight: bold" href="https://www.neowiz.com/neowiz">NEOWIZ</a>와 <a style="font-weight: bold" >ROCKY STUDIO</a>에게 속해있으며, 해당 데이터를 본 사이트 외에서 이용하여 생기는 모든 책임은 <span style="font-weight: bold">전적으로 본인에게 있습니다.</span><br>
        <a style="font-weight: bold">DJMAX RESPECT V</a>은 <span style="font-weight: bold">NEOWIZ</span>의 등록상표입니다.<br>

        본 사이트의 체감 난이도 값은 <a style="font-weight: bold" href="https://v-archive.net/">V-ARCHIVE</a>를 참고하여 작성되었습니다.
</div>
{% endblock %}